runtime: nodejs20
env: standard

instance_class: F1

handlers:
  # Serve the static files from the React build
  - url: /static
    static_dir: frontend/build/static
    secure: always

  - url: /manifest.json
    static_files: frontend/build/manifest.json
    upload: frontend/build/manifest.json
    secure: always
    
  - url: /favicon.ico
    static_files: frontend/build/favicon.ico
    upload: frontend/build/favicon.ico
    secure: always
    
  - url: /logo192.png
    static_files: frontend/build/logo192.png
    upload: frontend/build/logo192.png
    secure: always
    
  - url: /logo512.png
    static_files: frontend/build/logo512.png
    upload: frontend/build/logo512.png
    secure: always

  - url: /founder-jlasalle.png
    static_files: frontend/build/founder-jlasalle.png
    upload: frontend/build/founder-jlasalle.png
    secure: always
    
  - url: /robots.txt
    static_files: frontend/build/robots.txt
    upload: frontend/build/robots.txt
    secure: always
    
  - url: /sitemap.xml
    static_files: frontend/build/sitemap.xml
    upload: frontend/build/sitemap.xml
    secure: always

  # API routes handled by backend
  - url: /api/.*
    script: auto
    secure: always
    
  # Health check endpoint
  - url: /health
    script: auto
    secure: always

  # All other routes serve the React app
  - url: /.*
    static_files: frontend/build/index.html
    upload: frontend/build/index.html
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65